// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYg9g5BkgqLHPN_5n5DMICv_ritju0orA',
    appId: '1:946776847808:web:0696ca2e15ea338cbd4425',
    messagingSenderId: '946776847808',
    projectId: 'drp-project-41',
    authDomain: 'drp-project-41.firebaseapp.com',
    storageBucket: 'drp-project-41.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDT6hlHdPLVL1ZCwnRZokqTFsnQWFoCJJg',
    appId: '1:946776847808:android:0d62b932840ef626bd4425',
    messagingSenderId: '946776847808',
    projectId: 'drp-project-41',
    storageBucket: 'drp-project-41.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8qE70kqgPpPzx42VHHF1tK8cJAGpD-gM',
    appId: '1:946776847808:ios:10fa779f3518bb4abd4425',
    messagingSenderId: '946776847808',
    projectId: 'drp-project-41',
    storageBucket: 'drp-project-41.appspot.com',
    iosBundleId: 'com.example.drplanguageapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8qE70kqgPpPzx42VHHF1tK8cJAGpD-gM',
    appId: '1:946776847808:ios:10fa779f3518bb4abd4425',
    messagingSenderId: '946776847808',
    projectId: 'drp-project-41',
    storageBucket: 'drp-project-41.appspot.com',
    iosBundleId: 'com.example.drplanguageapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYg9g5BkgqLHPN_5n5DMICv_ritju0orA',
    appId: '1:946776847808:web:b8662b90e8fbfbc2bd4425',
    messagingSenderId: '946776847808',
    projectId: 'drp-project-41',
    authDomain: 'drp-project-41.firebaseapp.com',
    storageBucket: 'drp-project-41.appspot.com',
  );

}